require: rubocop-rspec

AllCops:
  Exclude:
    - 'Gemfile'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    
Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120  

Metrics/MethodLength:
  Max: 12

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'  

Naming/FileName:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent

