require:
  - rubocop-rspec
  - rubocop-performance 

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  Exclude:
    - 'Gemfile'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'lib/gem_ext/wondeclient/endpoints.rb'
    - !ruby/regexp /old_and_unused\.rb$/
  NewCops: enable  
    
RSpec/NamedSubject:
  Enabled: false
  
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'omniauth-wonde/lib/omniauth/strategies/wonde.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'lib/ext/Wondeclient/**/*.rb'

Metrics/MethodLength:
  Max: 12

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'  

Naming/FileName:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
