language: ruby
rvm:
  - 2.5.1
services:
  - postgresql
env:
  - travis=true
addons:
  postgresql: "9.5"
  chrome: stable
before_script:
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test bundle exec rails webpacker:compile
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
notifications:
  email: false