---
sudo: false
language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
services:
  - postgresql
addons:
  postgresql: "9.5"
  chrome: stable
before_install:
  - gem update --system
  - gem install bundler -v '~> 1.17'
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - bin/rails webpacker:compile
  - bin/rails db:create
  - bin/rails db:schema:load
script:
  - bundle exec rspec
notifications:
  email: false
