language: ruby
services:
  - postgresql
env:
  - travis=true
addons:
  postgresql: "9.5"
  chrome: stable
before_install:
  - gem update --system
  - gem install bundler -v '~> 1.17'
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test bundle exec rails webpacker:compile
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
notifications:
  email: false