---
env:
  global:
    - CC_TEST_REPORTER_ID=db925d9378f9ac6ee5e9410226e38c374e1b4460bfe82e76f12d21f26ff9b2f2
sudo: false
language: ruby
cache:
  bundler: true
  yarn: true
services:
  - postgresql
addons:
  postgresql: "9.5"
  chrome: stable
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bin/rails webpacker:compile
  - bin/rails db:create
  - bin/rails db:schema:load
script:
  - bundle exec rails webpacker:compile
  - bundle exec rspec
notifications:
  email: false
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_failure:
  - tail --lines=2000 log/test.log
