import "@hotwired/turbo-rails"
import "@rails/activestorage"
import "@rails/actioncable"
import "trix"
import "@rails/actiontext"

import "controllers"

import "./controller_info.js"
import "./classroom.js"
import "./homework.js"
import "./pages.js"
import "./schools.js"
import "./student_dashboard.js"
import "./teacher_dashboard.js"
import "./users.js"
import "./questions/multiple_choice_question.js"
import "./questions/question_top.js"
import "./questions/short_response_question.js"
import "./questions/import_topic_questions.js"
import "./lessons.js"
import "./questions.js"
import "./google_analytics.js"
